import"./assets/footer-C6MpvTPq.js";const k="favoriteRecipes";function w(){const t=localStorage.getItem(k);return t?JSON.parse(t):[]}function F(t){let e=w();e=e.filter(n=>n._id!==t),localStorage.setItem(k,JSON.stringify(e))}const h=document.querySelector("#favorite-recipes-container"),x=document.querySelector(".favorites-placeholder"),u=document.querySelector(".categories-filter"),b=document.querySelector("#favorites-pagination");let o=1,p=1;const y={first:'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="11 17 6 12 11 7"></polyline><polyline points="18 17 13 12 18 7"></polyline></svg>',prev:'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="15 18 9 12 15 6"></polyline></svg>',next:'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="9 18 15 12 9 6"></polyline></svg>',last:'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="13 17 18 12 13 7"></polyline><polyline points="6 17 11 12 6 7"></polyline></svg>'};function S(){const t=w(),e=[...new Set(t.map(s=>s.category))];let n='<button class="categories-box category-btn active" type="button">All categories</button>';e.forEach(s=>{n+=`
      <button class="categories-box category-btn" type="button">
        ${s}
      </button>
    `}),u.innerHTML=n}function E(){return window.innerWidth>=768?12:9}function M(){if(b.innerHTML="",p<=1)return;const t=document.createDocumentFragment(),e=(a,l,c=!1)=>{const i=document.createElement("button");return i.innerHTML=a,i.className=l,c&&(i.disabled=!0),i};t.appendChild(e(y.first,"pagination-btn prev-first",o===1)),t.appendChild(e(y.prev,"pagination-btn prev",o===1));const n=new Set;n.add(1),n.add(p),n.add(o),o>1&&n.add(o-1),o<p&&n.add(o+1);const s=Array.from(n).filter(a=>a>0&&a<=p).sort((a,l)=>a-l);let r=0;for(const a of s){if(r!==0&&a>r+1){const c=document.createElement("span");c.textContent="...",c.className="pagination-ellipsis",t.appendChild(c)}const l=e(a,"pagination-number");a===o&&l.classList.add("active"),t.appendChild(l),r=a}t.appendChild(e(y.next,"pagination-btn next",o===p)),t.appendChild(e(y.last,"pagination-btn next-last",o===p)),b.appendChild(t)}function g(t="All categories",e=1){let n=w();t!=="All categories"&&(n=n.filter(i=>i.category===t));const s=E();if(p=Math.ceil(n.length/s),o=e,n.length===0){x.classList.remove("hidden"),h.classList.add("hidden"),u.classList.add("hidden"),b.innerHTML="";return}x.classList.add("hidden"),h.classList.remove("hidden"),u.classList.remove("hidden");const r=(e-1)*s,a=r+s,c=n.slice(r,a).map(i=>{const m=i.rating/5*100;return`
      <div class="favorite-recipe-card" data-id="${i._id}" data-category="${i.category}">
        <button class="heart-btn favorite-heart-btn active" aria-label="Remove from favorites">
          <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"></path>
          </svg>
        </button>
        <img class="favorite-recipe-card-image" src="${i.thumb}" alt="${i.title}" loading="lazy">
        <div class="favorite-recipe-card-details">
          <h3 class="recipe-title favorite-recipe-title">${i.title}</h3>
          <p class="recipe-text favorite-recipe-text">${i.description}</p>
          <div class="favorite-recipe-card-footer">
            <div class="recipe-card-rating rating-box">
              <span class="rating-value">${(i.rating||0).toFixed(1)}</span>
              <div class="rating-stars" style="--rating: ${m}%">
                <span>★★★★★</span>
                <span class="stars-filled">★★★★★</span>
              </div>
            </div>
            <button class="see-recipe-btn" type="button">See recipe</button>
          </div>
        </div>
      </div>
    `}).join("");h.innerHTML=c,M()}function q(t){const e=t.target.closest(".favorite-heart-btn");if(!e)return;const n=e.closest(".favorite-recipe-card");if(!n)return;const s=document.querySelector(".category-btn.active"),r=s?s.textContent.trim():"All categories",a=n.dataset.id;let l=o;F(a),S();let c=w();r!=="All categories"&&(c=c.filter(f=>f.category===r));const i=E(),m=Math.ceil(c.length/i);l>m&&(l=m||1);const B=u.querySelectorAll(".category-btn");let C=!1;if(B.forEach(f=>{f.textContent.trim()===r?(C=!0,f.classList.add("active")):f.classList.remove("active")}),C)g(r,l);else{const f=u.querySelector(".category-btn");f&&f.classList.add("active"),g("All categories",1)}}function T(t){if(!t.target.matches(".category-btn"))return;const e=t.target.textContent.trim();u.querySelectorAll(".category-btn").forEach(n=>{n.classList.remove("active")}),t.target.classList.add("active"),g(e,1)}b.addEventListener("click",t=>{const e=t.target.closest(".pagination-btn, .pagination-number");e&&(e.classList.contains("pagination-number")&&g(v(),Number(e.textContent)),e.classList.contains("prev-first")&&g(v(),1),e.classList.contains("prev")&&o>1&&g(v(),o-1),e.classList.contains("next")&&o<p&&g(v(),o+1),e.classList.contains("next-last")&&g(v(),p))});function v(){const t=document.querySelector(".category-btn.active");return t?t.textContent.trim():"All categories"}function N(){S(),g()}const d=document.querySelector(".categories-filter");let L=!1,A,P;d.addEventListener("mousedown",t=>{L=!0,d.classList.add("grabbing"),A=t.pageX-d.offsetLeft,P=d.scrollLeft});d.addEventListener("mouseleave",()=>{L=!1,d.classList.remove("grabbing")});d.addEventListener("mouseup",()=>{L=!1,d.classList.remove("grabbing")});d.addEventListener("mousemove",t=>{if(!L)return;t.preventDefault();const n=(t.pageX-d.offsetLeft-A)*2;d.scrollLeft=P-n});document.addEventListener("DOMContentLoaded",N);h.addEventListener("click",q);u.addEventListener("click",T);window.addEventListener("resize",()=>{g(v(),1)});
//# sourceMappingURL=favorites.js.map
