import"./assets/footer-Cw73Jzmf.js";const k="favoriteRecipes";function w(){const e=localStorage.getItem(k);return e?JSON.parse(e):[]}function F(e){let t=w();t=t.filter(n=>n._id!==e),localStorage.setItem(k,JSON.stringify(t))}const h=document.querySelector("#favorite-recipes-container"),x=document.querySelector(".favorites-placeholder"),u=document.querySelector(".categories-filter"),b=document.querySelector("#favorites-pagination");let o=1,p=1;const y={first:'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="11 17 6 12 11 7"></polyline><polyline points="18 17 13 12 18 7"></polyline></svg>',prev:'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="15 18 9 12 15 6"></polyline></svg>',next:'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="9 18 15 12 9 6"></polyline></svg>',last:'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="13 17 18 12 13 7"></polyline><polyline points="6 17 11 12 6 7"></polyline></svg>'};function S(){const e=w(),t=[...new Set(e.map(a=>a.category))];let n='<button class="categories-box category-btn active" type="button">All categories</button>';t.forEach(a=>{n+=`
      <button class="categories-box category-btn" type="button">
        ${a}
      </button>
    `}),u.innerHTML=n}function E(){const e=window.innerWidth;return e>=1440?15:e>=768?12:9}function M(){if(b.innerHTML="",p<=1)return;const e=document.createDocumentFragment(),t=(s,l,c=!1)=>{const i=document.createElement("button");return i.innerHTML=s,i.className=l,c&&(i.disabled=!0),i};e.appendChild(t(y.first,"pagination-btn prev-first",o===1)),e.appendChild(t(y.prev,"pagination-btn prev",o===1));const n=new Set;n.add(1),n.add(p),n.add(o),o>1&&n.add(o-1),o<p&&n.add(o+1);const a=Array.from(n).filter(s=>s>0&&s<=p).sort((s,l)=>s-l);let r=0;for(const s of a){if(r!==0&&s>r+1){const c=document.createElement("span");c.textContent="...",c.className="pagination-ellipsis",e.appendChild(c)}const l=t(s,"pagination-number");s===o&&l.classList.add("active"),e.appendChild(l),r=s}e.appendChild(t(y.next,"pagination-btn next",o===p)),e.appendChild(t(y.last,"pagination-btn next-last",o===p)),b.appendChild(e)}function g(e="All categories",t=1){let n=w();e!=="All categories"&&(n=n.filter(i=>i.category===e));const a=E();if(p=Math.ceil(n.length/a),o=t,n.length===0){x.classList.remove("hidden"),h.classList.add("hidden"),u.classList.add("hidden"),b.innerHTML="";return}x.classList.add("hidden"),h.classList.remove("hidden"),u.classList.remove("hidden");const r=(t-1)*a,s=r+a,c=n.slice(r,s).map(i=>{const m=i.rating/5*100;return`
      <div class="favorite-recipe-card" data-id="${i._id}" data-category="${i.category}">
        <button class="heart-btn favorite-heart-btn active" aria-label="Remove from favorites">
          <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"></path>
          </svg>
        </button>
        <img class="favorite-recipe-card-image" src="${i.thumb}" alt="${i.title}" loading="lazy">
        <div class="favorite-recipe-card-details">
          <h3 class="recipe-title favorite-recipe-title">${i.title}</h3>
          <p class="recipe-text favorite-recipe-text">${i.description}</p>
          <div class="favorite-recipe-card-footer">
            <div class="recipe-card-rating rating-box">
              <span class="rating-value">${(i.rating||0).toFixed(1)}</span>
              <div class="rating-stars" style="--rating: ${m}%">
                <span>★★★★★</span>
                <span class="stars-filled">★★★★★</span>
              </div>
            </div>
            <button class="see-recipe-btn" type="button">See recipe</button>
          </div>
        </div>
      </div>
    `}).join("");h.innerHTML=c,M()}function q(e){const t=e.target.closest(".favorite-heart-btn");if(!t)return;const n=t.closest(".favorite-recipe-card");if(!n)return;const a=document.querySelector(".category-btn.active"),r=a?a.textContent.trim():"All categories",s=n.dataset.id;let l=o;F(s),S();let c=w();r!=="All categories"&&(c=c.filter(f=>f.category===r));const i=E(),m=Math.ceil(c.length/i);l>m&&(l=m||1);const B=u.querySelectorAll(".category-btn");let C=!1;if(B.forEach(f=>{f.textContent.trim()===r?(C=!0,f.classList.add("active")):f.classList.remove("active")}),C)g(r,l);else{const f=u.querySelector(".category-btn");f&&f.classList.add("active"),g("All categories",1)}}function T(e){if(!e.target.matches(".category-btn"))return;const t=e.target.textContent.trim();u.querySelectorAll(".category-btn").forEach(n=>{n.classList.remove("active")}),e.target.classList.add("active"),g(t,1)}b.addEventListener("click",e=>{const t=e.target.closest(".pagination-btn, .pagination-number");t&&(t.classList.contains("pagination-number")&&g(v(),Number(t.textContent)),t.classList.contains("prev-first")&&g(v(),1),t.classList.contains("prev")&&o>1&&g(v(),o-1),t.classList.contains("next")&&o<p&&g(v(),o+1),t.classList.contains("next-last")&&g(v(),p))});function v(){const e=document.querySelector(".category-btn.active");return e?e.textContent.trim():"All categories"}function N(){S(),g()}const d=document.querySelector(".categories-filter");let L=!1,A,P;d.addEventListener("mousedown",e=>{L=!0,d.classList.add("grabbing"),A=e.pageX-d.offsetLeft,P=d.scrollLeft});d.addEventListener("mouseleave",()=>{L=!1,d.classList.remove("grabbing")});d.addEventListener("mouseup",()=>{L=!1,d.classList.remove("grabbing")});d.addEventListener("mousemove",e=>{if(!L)return;e.preventDefault();const n=(e.pageX-d.offsetLeft-A)*2;d.scrollLeft=P-n});document.addEventListener("DOMContentLoaded",N);h.addEventListener("click",q);u.addEventListener("click",T);window.addEventListener("resize",()=>{g(v(),1)});
//# sourceMappingURL=favorites.js.map
