/* empty css                      */(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const m="https://tasty-treats-backend.p.goit.global/api";async function g({category:n="",page:r=1,limit:i=6,time:s="",area:e="",ingredient:t=""}={}){const a=new URL(`${m}/recipes`);return n&&a.searchParams.append("category",n),r&&a.searchParams.append("page",r),i&&a.searchParams.append("limit",i),s&&a.searchParams.append("time",s),e&&a.searchParams.append("area",e),t&&a.searchParams.append("ingredient",t),await(await fetch(a)).json()}const d=document.querySelector("#recipes-container"),l=document.querySelector("#pagination");let o=1,f=1,c=p();function p(){const n=window.innerWidth;return n<768?6:n<1280?8:9}async function u(n=1){try{c=p();const r=await g({page:n,limit:c}),i=r.results;if(f=r.totalPages||Math.ceil(r.totalResults/c),!i||i.length===0){d.innerHTML="<p>No recipes found to display.</p>",l.innerHTML="";return}const s=i.map(e=>`
        <div class="recipe-card" data-id="${e._id}">
          <img class="recipe-card-image" src="${e.thumb}" alt="${e.title}" loading="lazy">
          <div class="recipe-card-content">
            <h3 class="recipe-card-title">${e.title}</h3>
            <p class="recipe-card-description">${e.description}</p>
            <div class="recipe-card-rating">
              <span>${e.rating.toFixed(1)}</span>
            </div>
            <button class="recipe-card-button" type="button">See recipe</button>
          </div>
        </div>`).join("");d.innerHTML=s,h(f,n)}catch(r){console.error("An error occurred while loading recipes:",r),d.innerHTML="<p>The recipes could not be loaded. Please try again later.</p>",l.innerHTML=""}}function h(n,r){let i="";for(let e=1;e<=n;e++)i+=`<button class="pagination-btn ${e===r?"active":""}" data-page="${e}">${e}</button>`;l.innerHTML=i,l.querySelectorAll(".pagination-btn").forEach(e=>{e.addEventListener("click",()=>{const t=Number(e.dataset.page);t!==o&&(o=t,u(o))})})}window.addEventListener("resize",()=>{p()!==c&&(o=1,u(o))});u();
//# sourceMappingURL=index.js.map
